### ISSUE TITLE
Is there any way to support swift 2.3?

### ISSUE THREAD

**Issue by thihaaung6245** [Sufi-Al-Hussaini/Swift-CircleMenu#1]
First of all, thanks for offering your knowledge. I have been searching such feature for a long day with failure until I found yours. Easy to learn cause this was in SWIFT!!!. I looked raywenderlich tutorials and other libraries. Everything is in Objective C. Special Thanks to you.

But, since my project is currently running on Xcode 7.3.1, can you make your project in Swift 2.3? iOS 8 support?

**Comment by hu55a1n1** [comment]
Hi, 

Sorry, but I'm a little busy with my other projects these days, so supporting Swift 2.3 isn't possible right now. 
That being said, I think it should be pretty straightforward, requiring only syntactical changes. You could import this library into your Swift 2.3 project and correct the errors one at a time. 

Most libraries support legacy swift versions on separate branches. 
I could create a `swift-2.3` branch for you and I'll be happy to accept pull requests.

If there's anything else I can help with, please don't hesitate to ask.

**Comment by thihaaung6245** [comment]
Ok, I will try to contribute.
